/* Do not edit. File generated by rastro. */

#ifndef __AUTO_RASTRO_FILE_H__
#define __AUTO_RASTRO_FILE_H__
#include <rastro.h>

/* Rastro function prototype for 'sss' */
void rst_event_sss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, const char* s2);
void rst_event_sss_f_ (int16_t *type, const char* s0, const char* s1, const char* s2);
#define rst_event_sss(type, s0, s1, s2) rst_event_sss_ptr(RST_PTR, type, s0, s1, s2)

/* Rastro function prototype for 'ssss' */
void rst_event_ssss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, const char* s2, const char* s3);
void rst_event_ssss_f_ (int16_t *type, const char* s0, const char* s1, const char* s2, const char* s3);
#define rst_event_ssss(type, s0, s1, s2, s3) rst_event_ssss_ptr(RST_PTR, type, s0, s1, s2, s3)

/* Rastro function prototype for 'sssss' */
void rst_event_sssss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4);
void rst_event_sssss_f_ (int16_t *type, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4);
#define rst_event_sssss(type, s0, s1, s2, s3, s4) rst_event_sssss_ptr(RST_PTR, type, s0, s1, s2, s3, s4)

/* Rastro function prototype for 'sssss' */
void rst_event_sssss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4);
void rst_event_sssss_f_ (int16_t *type, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4);
#define rst_event_sssss(type, s0, s1, s2, s3, s4) rst_event_sssss_ptr(RST_PTR, type, s0, s1, s2, s3, s4)

/* Rastro function prototype for 'sss' */
void rst_event_sss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, const char* s2);
void rst_event_sss_f_ (int16_t *type, const char* s0, const char* s1, const char* s2);
#define rst_event_sss(type, s0, s1, s2) rst_event_sss_ptr(RST_PTR, type, s0, s1, s2)

/* Rastro function prototype for 'ssss' */
void rst_event_ssss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, const char* s2, const char* s3);
void rst_event_ssss_f_ (int16_t *type, const char* s0, const char* s1, const char* s2, const char* s3);
#define rst_event_ssss(type, s0, s1, s2, s3) rst_event_ssss_ptr(RST_PTR, type, s0, s1, s2, s3)

/* Rastro function prototype for 'ssss' */
void rst_event_ssss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, const char* s2, const char* s3);
void rst_event_ssss_f_ (int16_t *type, const char* s0, const char* s1, const char* s2, const char* s3);
#define rst_event_ssss(type, s0, s1, s2, s3) rst_event_ssss_ptr(RST_PTR, type, s0, s1, s2, s3)

/* Rastro function prototype for 'sssss' */
void rst_event_sssss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4);
void rst_event_sssss_f_ (int16_t *type, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4);
#define rst_event_sssss(type, s0, s1, s2, s3, s4) rst_event_sssss_ptr(RST_PTR, type, s0, s1, s2, s3, s4)

/* Rastro function prototype for 'ssssss' */
void rst_event_ssssss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, const char* s5);
void rst_event_ssssss_f_ (int16_t *type, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, const char* s5);
#define rst_event_ssssss(type, s0, s1, s2, s3, s4, s5) rst_event_ssssss_ptr(RST_PTR, type, s0, s1, s2, s3, s4, s5)

/* Rastro function prototype for 'sssssss' */
void rst_event_sssssss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, const char* s5, const char* s6);
void rst_event_sssssss_f_ (int16_t *type, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, const char* s5, const char* s6);
#define rst_event_sssssss(type, s0, s1, s2, s3, s4, s5, s6) rst_event_sssssss_ptr(RST_PTR, type, s0, s1, s2, s3, s4, s5, s6)

/* Rastro function prototype for 'ssssssss' */
void rst_event_ssssssss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, const char* s5, const char* s6, const char* s7);
void rst_event_ssssssss_f_ (int16_t *type, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, const char* s5, const char* s6, const char* s7);
#define rst_event_ssssssss(type, s0, s1, s2, s3, s4, s5, s6, s7) rst_event_ssssssss_ptr(RST_PTR, type, s0, s1, s2, s3, s4, s5, s6, s7)

void rst_init_f_(int64_t *id1, int64_t *id2);
void rst_finalize_f_ (void);

#endif //__AUTO_RASTRO_FILE_H__
