/* Do not edit. File generated by rastro. */

#ifndef __AUTO_RASTRO_FILE_H__
#define __AUTO_RASTRO_FILE_H__
#include <rastro.h>

/* Rastro function prototype for 'iiiiiii' */
void rst_event_iiiiiii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1, u_int32_t i2, u_int32_t i3, u_int32_t i4, u_int32_t i5, u_int32_t i6);
void rst_event_iiiiiii_f_ (int16_t *type, int32_t* i0, int32_t* i1, int32_t* i2, int32_t* i3, int32_t* i4, int32_t* i5, int32_t* i6);
#define rst_event_iiiiiii(type, i0, i1, i2, i3, i4, i5, i6) rst_event_iiiiiii_ptr(RST_PTR, type, i0, i1, i2, i3, i4, i5, i6)

/* Rastro function prototype for 'iiiiiiiii' */
void rst_event_iiiiiiiii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1, u_int32_t i2, u_int32_t i3, u_int32_t i4, u_int32_t i5, u_int32_t i6, u_int32_t i7, u_int32_t i8);
void rst_event_iiiiiiiii_f_ (int16_t *type, int32_t* i0, int32_t* i1, int32_t* i2, int32_t* i3, int32_t* i4, int32_t* i5, int32_t* i6, int32_t* i7, int32_t* i8);
#define rst_event_iiiiiiiii(type, i0, i1, i2, i3, i4, i5, i6, i7, i8) rst_event_iiiiiiiii_ptr(RST_PTR, type, i0, i1, i2, i3, i4, i5, i6, i7, i8)

/* Rastro function prototype for 'iiiiiiiiiii' */
void rst_event_iiiiiiiiiii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1, u_int32_t i2, u_int32_t i3, u_int32_t i4, u_int32_t i5, u_int32_t i6, u_int32_t i7, u_int32_t i8, u_int32_t i9, u_int32_t i10);
void rst_event_iiiiiiiiiii_f_ (int16_t *type, int32_t* i0, int32_t* i1, int32_t* i2, int32_t* i3, int32_t* i4, int32_t* i5, int32_t* i6, int32_t* i7, int32_t* i8, int32_t* i9, int32_t* i10);
#define rst_event_iiiiiiiiiii(type, i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10) rst_event_iiiiiiiiiii_ptr(RST_PTR, type, i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10)

/* Rastro function prototype for 'iiiiiiiiiiiii' */
void rst_event_iiiiiiiiiiiii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1, u_int32_t i2, u_int32_t i3, u_int32_t i4, u_int32_t i5, u_int32_t i6, u_int32_t i7, u_int32_t i8, u_int32_t i9, u_int32_t i10, u_int32_t i11, u_int32_t i12);
void rst_event_iiiiiiiiiiiii_f_ (int16_t *type, int32_t* i0, int32_t* i1, int32_t* i2, int32_t* i3, int32_t* i4, int32_t* i5, int32_t* i6, int32_t* i7, int32_t* i8, int32_t* i9, int32_t* i10, int32_t* i11, int32_t* i12);
#define rst_event_iiiiiiiiiiiii(type, i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12) rst_event_iiiiiiiiiiiii_ptr(RST_PTR, type, i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12)

/* Rastro function prototype for 'iiiiiiiiiiiiiii' */
void rst_event_iiiiiiiiiiiiiii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1, u_int32_t i2, u_int32_t i3, u_int32_t i4, u_int32_t i5, u_int32_t i6, u_int32_t i7, u_int32_t i8, u_int32_t i9, u_int32_t i10, u_int32_t i11, u_int32_t i12, u_int32_t i13, u_int32_t i14);
void rst_event_iiiiiiiiiiiiiii_f_ (int16_t *type, int32_t* i0, int32_t* i1, int32_t* i2, int32_t* i3, int32_t* i4, int32_t* i5, int32_t* i6, int32_t* i7, int32_t* i8, int32_t* i9, int32_t* i10, int32_t* i11, int32_t* i12, int32_t* i13, int32_t* i14);
#define rst_event_iiiiiiiiiiiiiii(type, i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i13, i14) rst_event_iiiiiiiiiiiiiii_ptr(RST_PTR, type, i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i13, i14)

/* Rastro function prototype for 'iiiiiiiiiiiiiiiii' */
void rst_event_iiiiiiiiiiiiiiiii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1, u_int32_t i2, u_int32_t i3, u_int32_t i4, u_int32_t i5, u_int32_t i6, u_int32_t i7, u_int32_t i8, u_int32_t i9, u_int32_t i10, u_int32_t i11, u_int32_t i12, u_int32_t i13, u_int32_t i14, u_int32_t i15, u_int32_t i16);
void rst_event_iiiiiiiiiiiiiiiii_f_ (int16_t *type, int32_t* i0, int32_t* i1, int32_t* i2, int32_t* i3, int32_t* i4, int32_t* i5, int32_t* i6, int32_t* i7, int32_t* i8, int32_t* i9, int32_t* i10, int32_t* i11, int32_t* i12, int32_t* i13, int32_t* i14, int32_t* i15, int32_t* i16);
#define rst_event_iiiiiiiiiiiiiiiii(type, i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i13, i14, i15, i16) rst_event_iiiiiiiiiiiiiiiii_ptr(RST_PTR, type, i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i13, i14, i15, i16)



#endif //__AUTO_RASTRO_FILE_H__
