/* Do not edit. File generated by rastro. */

#ifndef __AUTO_RASTRO_EVENTS_FILE_H__
#define __AUTO_RASTRO_EVENTS_FILE_H__
#include <rastro.h>

/* Rastro function prototype for 'sss' */
void rst_event_sss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, const char* s2);
void rst_event_sss_f_ (int16_t *type, const char* s0, const char* s1, const char* s2);
#define rst_event_sss(type, s0, s1, s2) rst_event_sss_ptr(RST_PTR, type, s0, s1, s2)

/* Rastro function prototype for 'ssss' */
void rst_event_ssss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, const char* s2, const char* s3);
void rst_event_ssss_f_ (int16_t *type, const char* s0, const char* s1, const char* s2, const char* s3);
#define rst_event_ssss(type, s0, s1, s2, s3) rst_event_ssss_ptr(RST_PTR, type, s0, s1, s2, s3)

/* Rastro function prototype for 'sssss' */
void rst_event_sssss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4);
void rst_event_sssss_f_ (int16_t *type, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4);
#define rst_event_sssss(type, s0, s1, s2, s3, s4) rst_event_sssss_ptr(RST_PTR, type, s0, s1, s2, s3, s4)

/* Rastro function prototype for 'dssss' */
void rst_event_dssss_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1, const char* s2, const char* s3);
void rst_event_dssss_f_ (int16_t *type, double* d0, const char* s0, const char* s1, const char* s2, const char* s3);
#define rst_event_dssss(type, d0, s0, s1, s2, s3) rst_event_dssss_ptr(RST_PTR, type, d0, s0, s1, s2, s3)

/* Rastro function prototype for 'dss' */
void rst_event_dss_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1);
void rst_event_dss_f_ (int16_t *type, double* d0, const char* s0, const char* s1);
#define rst_event_dss(type, d0, s0, s1) rst_event_dss_ptr(RST_PTR, type, d0, s0, s1)

/* Rastro function prototype for 'dssd' */
void rst_event_dssd_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1, double d1);
void rst_event_dssd_f_ (int16_t *type, double* d0, const char* s0, const char* s1, double* d1);
#define rst_event_dssd(type, d0, s0, s1, d1) rst_event_dssd_ptr(RST_PTR, type, d0, s0, s1, d1)

/* Rastro function prototype for 'dsss' */
void rst_event_dsss_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1, const char* s2);
void rst_event_dsss_f_ (int16_t *type, double* d0, const char* s0, const char* s1, const char* s2);
#define rst_event_dsss(type, d0, s0, s1, s2) rst_event_dsss_ptr(RST_PTR, type, d0, s0, s1, s2)

/* Rastro function prototype for 'dsssi' */
void rst_event_dsssi_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1, const char* s2, u_int32_t i0);
void rst_event_dsssi_f_ (int16_t *type, double* d0, const char* s0, const char* s1, const char* s2, int32_t* i0);
#define rst_event_dsssi(type, d0, s0, s1, s2, i0) rst_event_dsssi_ptr(RST_PTR, type, d0, s0, s1, s2, i0)

/* Rastro function prototype for 'dsssss' */
void rst_event_dsssss_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4);
void rst_event_dsssss_f_ (int16_t *type, double* d0, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4);
#define rst_event_dsssss(type, d0, s0, s1, s2, s3, s4) rst_event_dsssss_ptr(RST_PTR, type, d0, s0, s1, s2, s3, s4)

/* Rastro function prototype for 'dsssssi' */
void rst_event_dsssssi_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, u_int32_t i0);
void rst_event_dsssssi_f_ (int16_t *type, double* d0, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, int32_t* i0);
#define rst_event_dsssssi(type, d0, s0, s1, s2, s3, s4, i0) rst_event_dsssssi_ptr(RST_PTR, type, d0, s0, s1, s2, s3, s4, i0)

/* Rastro function prototype for 'dsssssii' */
void rst_event_dsssssii_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, u_int32_t i0, u_int32_t i1);
void rst_event_dsssssii_f_ (int16_t *type, double* d0, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, int32_t* i0, int32_t* i1);
#define rst_event_dsssssii(type, d0, s0, s1, s2, s3, s4, i0, i1) rst_event_dsssssii_ptr(RST_PTR, type, d0, s0, s1, s2, s3, s4, i0, i1)




/* Rastro function prototype for 'ccc' */
void rst_event_ccc_ptr(rst_buffer_t *ptr, u_int16_t type, u_int8_t c0, u_int8_t c1, u_int8_t c2);
void rst_event_ccc_f_ (int16_t *type, int8_t* c0, int8_t* c1, int8_t* c2);
#define rst_event_ccc(type, c0, c1, c2) rst_event_ccc_ptr(RST_PTR, type, c0, c1, c2)

/* Rastro function prototype for 'cccc' */
void rst_event_cccc_ptr(rst_buffer_t *ptr, u_int16_t type, u_int8_t c0, u_int8_t c1, u_int8_t c2, u_int8_t c3);
void rst_event_cccc_f_ (int16_t *type, int8_t* c0, int8_t* c1, int8_t* c2, int8_t* c3);
#define rst_event_cccc(type, c0, c1, c2, c3) rst_event_cccc_ptr(RST_PTR, type, c0, c1, c2, c3)

/* Rastro function prototype for 'ccccc' */
void rst_event_ccccc_ptr(rst_buffer_t *ptr, u_int16_t type, u_int8_t c0, u_int8_t c1, u_int8_t c2, u_int8_t c3, u_int8_t c4);
void rst_event_ccccc_f_ (int16_t *type, int8_t* c0, int8_t* c1, int8_t* c2, int8_t* c3, int8_t* c4);
#define rst_event_ccccc(type, c0, c1, c2, c3, c4) rst_event_ccccc_ptr(RST_PTR, type, c0, c1, c2, c3, c4)

/* Rastro function prototype for 'dcccc' */
void rst_event_dcccc_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, u_int8_t c0, u_int8_t c1, u_int8_t c2, u_int8_t c3);
void rst_event_dcccc_f_ (int16_t *type, double* d0, int8_t* c0, int8_t* c1, int8_t* c2, int8_t* c3);
#define rst_event_dcccc(type, d0, c0, c1, c2, c3) rst_event_dcccc_ptr(RST_PTR, type, d0, c0, c1, c2, c3)

/* Rastro function prototype for 'dcc' */
void rst_event_dcc_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, u_int8_t c0, u_int8_t c1);
void rst_event_dcc_f_ (int16_t *type, double* d0, int8_t* c0, int8_t* c1);
#define rst_event_dcc(type, d0, c0, c1) rst_event_dcc_ptr(RST_PTR, type, d0, c0, c1)

/* Rastro function prototype for 'dccd' */
void rst_event_dccd_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, u_int8_t c0, u_int8_t c1, double d1);
void rst_event_dccd_f_ (int16_t *type, double* d0, int8_t* c0, int8_t* c1, double* d1);
#define rst_event_dccd(type, d0, c0, c1, d1) rst_event_dccd_ptr(RST_PTR, type, d0, c0, c1, d1)

/* Rastro function prototype for 'dccc' */
void rst_event_dccc_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, u_int8_t c0, u_int8_t c1, u_int8_t c2);
void rst_event_dccc_f_ (int16_t *type, double* d0, int8_t* c0, int8_t* c1, int8_t* c2);
#define rst_event_dccc(type, d0, c0, c1, c2) rst_event_dccc_ptr(RST_PTR, type, d0, c0, c1, c2)

/* Rastro function prototype for 'dccci' */
void rst_event_dccci_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, u_int8_t c0, u_int8_t c1, u_int8_t c2, u_int32_t i0);
void rst_event_dccci_f_ (int16_t *type, double* d0, int8_t* c0, int8_t* c1, int8_t* c2, int32_t* i0);
#define rst_event_dccci(type, d0, c0, c1, c2, i0) rst_event_dccci_ptr(RST_PTR, type, d0, c0, c1, c2, i0)

/* Rastro function prototype for 'dccccc' */
void rst_event_dccccc_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, u_int8_t c0, u_int8_t c1, u_int8_t c2, u_int8_t c3, u_int8_t c4);
void rst_event_dccccc_f_ (int16_t *type, double* d0, int8_t* c0, int8_t* c1, int8_t* c2, int8_t* c3, int8_t* c4);
#define rst_event_dccccc(type, d0, c0, c1, c2, c3, c4) rst_event_dccccc_ptr(RST_PTR, type, d0, c0, c1, c2, c3, c4)

/* Rastro function prototype for 'dccccci' */
void rst_event_dccccci_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, u_int8_t c0, u_int8_t c1, u_int8_t c2, u_int8_t c3, u_int8_t c4, u_int32_t i0);
void rst_event_dccccci_f_ (int16_t *type, double* d0, int8_t* c0, int8_t* c1, int8_t* c2, int8_t* c3, int8_t* c4, int32_t* i0);
#define rst_event_dccccci(type, d0, c0, c1, c2, c3, c4, i0) rst_event_dccccci_ptr(RST_PTR, type, d0, c0, c1, c2, c3, c4, i0)

/* Rastro function prototype for 'dcccccii' */
void rst_event_dcccccii_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, u_int8_t c0, u_int8_t c1, u_int8_t c2, u_int8_t c3, u_int8_t c4, u_int32_t i0, u_int32_t i1);
void rst_event_dcccccii_f_ (int16_t *type, double* d0, int8_t* c0, int8_t* c1, int8_t* c2, int8_t* c3, int8_t* c4, int32_t* i0, int32_t* i1);
#define rst_event_dcccccii(type, d0, c0, c1, c2, c3, c4, i0, i1) rst_event_dcccccii_ptr(RST_PTR, type, d0, c0, c1, c2, c3, c4, i0, i1)

/* Rastro function prototype for 'cs' */
void rst_event_cs_ptr(rst_buffer_t *ptr, u_int16_t type, u_int8_t c0, const char* s0);
void rst_event_cs_f_ (int16_t *type, int8_t* c0, const char* s0);
#define rst_event_cs(type, c0, s0) rst_event_cs_ptr(RST_PTR, type, c0, s0)





/* USING 16 bits for reference counter */

/* Rastro function prototype for 'www' */
void rst_event_www_ptr(rst_buffer_t *ptr, u_int16_t type, u_int16_t w0, u_int16_t w1, u_int16_t w2);
void rst_event_www_f_ (int16_t *type, int16_t* w0, int16_t* w1, int16_t* w2);
#define rst_event_www(type, w0, w1, w2) rst_event_www_ptr(RST_PTR, type, w0, w1, w2)

/* Rastro function prototype for 'wwww' */
void rst_event_wwww_ptr(rst_buffer_t *ptr, u_int16_t type, u_int16_t w0, u_int16_t w1, u_int16_t w2, u_int16_t w3);
void rst_event_wwww_f_ (int16_t *type, int16_t* w0, int16_t* w1, int16_t* w2, int16_t* w3);
#define rst_event_wwww(type, w0, w1, w2, w3) rst_event_wwww_ptr(RST_PTR, type, w0, w1, w2, w3)

/* Rastro function prototype for 'wwwww' */
void rst_event_wwwww_ptr(rst_buffer_t *ptr, u_int16_t type, u_int16_t w0, u_int16_t w1, u_int16_t w2, u_int16_t w3, u_int16_t w4);
void rst_event_wwwww_f_ (int16_t *type, int16_t* w0, int16_t* w1, int16_t* w2, int16_t* w3, int16_t* w4);
#define rst_event_wwwww(type, w0, w1, w2, w3, w4) rst_event_wwwww_ptr(RST_PTR, type, w0, w1, w2, w3, w4)

/* Rastro function prototype for 'dwwww' */
void rst_event_dwwww_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, u_int16_t w0, u_int16_t w1, u_int16_t w2, u_int16_t w3);
void rst_event_dwwww_f_ (int16_t *type, double* d0, int16_t* w0, int16_t* w1, int16_t* w2, int16_t* w3);
#define rst_event_dwwww(type, d0, w0, w1, w2, w3) rst_event_dwwww_ptr(RST_PTR, type, d0, w0, w1, w2, w3)

/* Rastro function prototype for 'dww' */
void rst_event_dww_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, u_int16_t w0, u_int16_t w1);
void rst_event_dww_f_ (int16_t *type, double* d0, int16_t* w0, int16_t* w1);
#define rst_event_dww(type, d0, w0, w1) rst_event_dww_ptr(RST_PTR, type, d0, w0, w1)

/* Rastro function prototype for 'dwwd' */
void rst_event_dwwd_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, u_int16_t w0, u_int16_t w1, double d1);
void rst_event_dwwd_f_ (int16_t *type, double* d0, int16_t* w0, int16_t* w1, double* d1);
#define rst_event_dwwd(type, d0, w0, w1, d1) rst_event_dwwd_ptr(RST_PTR, type, d0, w0, w1, d1)

/* Rastro function prototype for 'dwww' */
void rst_event_dwww_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, u_int16_t w0, u_int16_t w1, u_int16_t w2);
void rst_event_dwww_f_ (int16_t *type, double* d0, int16_t* w0, int16_t* w1, int16_t* w2);
#define rst_event_dwww(type, d0, w0, w1, w2) rst_event_dwww_ptr(RST_PTR, type, d0, w0, w1, w2)

/* Rastro function prototype for 'dwwwi' */
void rst_event_dwwwi_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, u_int16_t w0, u_int16_t w1, u_int16_t w2, u_int32_t i0);
void rst_event_dwwwi_f_ (int16_t *type, double* d0, int16_t* w0, int16_t* w1, int16_t* w2, int32_t* i0);
#define rst_event_dwwwi(type, d0, w0, w1, w2, i0) rst_event_dwwwi_ptr(RST_PTR, type, d0, w0, w1, w2, i0)

/* Rastro function prototype for 'dwwwww' */
void rst_event_dwwwww_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, u_int16_t w0, u_int16_t w1, u_int16_t w2, u_int16_t w3, u_int16_t w4);
void rst_event_dwwwww_f_ (int16_t *type, double* d0, int16_t* w0, int16_t* w1, int16_t* w2, int16_t* w3, int16_t* w4);
#define rst_event_dwwwww(type, d0, w0, w1, w2, w3, w4) rst_event_dwwwww_ptr(RST_PTR, type, d0, w0, w1, w2, w3, w4)

/* Rastro function prototype for 'dwwwwwi' */
void rst_event_dwwwwwi_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, u_int16_t w0, u_int16_t w1, u_int16_t w2, u_int16_t w3, u_int16_t w4, u_int32_t i0);
void rst_event_dwwwwwi_f_ (int16_t *type, double* d0, int16_t* w0, int16_t* w1, int16_t* w2, int16_t* w3, int16_t* w4, int32_t* i0);
#define rst_event_dwwwwwi(type, d0, w0, w1, w2, w3, w4, i0) rst_event_dwwwwwi_ptr(RST_PTR, type, d0, w0, w1, w2, w3, w4, i0)

/* Rastro function prototype for 'dwwwwwii' */
void rst_event_dwwwwwii_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, u_int16_t w0, u_int16_t w1, u_int16_t w2, u_int16_t w3, u_int16_t w4, u_int32_t i0, u_int32_t i1);
void rst_event_dwwwwwii_f_ (int16_t *type, double* d0, int16_t* w0, int16_t* w1, int16_t* w2, int16_t* w3, int16_t* w4, int32_t* i0, int32_t* i1);
#define rst_event_dwwwwwii(type, d0, w0, w1, w2, w3, w4, i0, i1) rst_event_dwwwwwii_ptr(RST_PTR, type, d0, w0, w1, w2, w3, w4, i0, i1)

/* Rastro function prototype for 'ws' */
void rst_event_ws_ptr(rst_buffer_t *ptr, u_int16_t type, u_int16_t w0, const char* s0);
void rst_event_ws_f_ (int16_t *type, int16_t* w0, const char* s0);
#define rst_event_ws(type, w0, s0) rst_event_ws_ptr(RST_PTR, type, w0, s0)


/* Rastro function prototype for 's' */
void rst_event_s_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0);
void rst_event_s_f_ (int16_t *type, const char* s0);
#define rst_event_s(type, s0) rst_event_s_ptr(RST_PTR, type, s0)



void rst_init_f_(int64_t *id1, int64_t *id2);
void rst_finalize_f_ (void);

#endif //__AUTO_RASTRO_EVENTS_FILE_H__
