/* Do not edit. File generated by rastro. */

#ifndef __AUTO_RASTRO_FILE_H__
#define __AUTO_RASTRO_FILE_H__
#include <rastro.h>

/* Rastro function prototype for 'dsss' */
void rst_event_dsss_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1, const char* s2);
void rst_event_dsss_f_ (int16_t *type, double* d0, const char* s0, const char* s1, const char* s2);
#define rst_event_dsss(type, d0, s0, s1, s2) rst_event_dsss_ptr(RST_PTR, type, d0, s0, s1, s2)

/* Rastro function prototype for 'dssss' */
void rst_event_dssss_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1, const char* s2, const char* s3);
void rst_event_dssss_f_ (int16_t *type, double* d0, const char* s0, const char* s1, const char* s2, const char* s3);
#define rst_event_dssss(type, d0, s0, s1, s2, s3) rst_event_dssss_ptr(RST_PTR, type, d0, s0, s1, s2, s3)

/* Rastro function prototype for 'dsssss' */
void rst_event_dsssss_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4);
void rst_event_dsssss_f_ (int16_t *type, double* d0, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4);
#define rst_event_dsssss(type, d0, s0, s1, s2, s3, s4) rst_event_dsssss_ptr(RST_PTR, type, d0, s0, s1, s2, s3, s4)

/* Rastro function prototype for 'ddssss' */
void rst_event_ddssss_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, double d1, const char* s0, const char* s1, const char* s2, const char* s3);
void rst_event_ddssss_f_ (int16_t *type, double* d0, double* d1, const char* s0, const char* s1, const char* s2, const char* s3);
#define rst_event_ddssss(type, d0, d1, s0, s1, s2, s3) rst_event_ddssss_ptr(RST_PTR, type, d0, d1, s0, s1, s2, s3)

/* Rastro function prototype for 'ddss' */
void rst_event_ddss_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, double d1, const char* s0, const char* s1);
void rst_event_ddss_f_ (int16_t *type, double* d0, double* d1, const char* s0, const char* s1);
#define rst_event_ddss(type, d0, d1, s0, s1) rst_event_ddss_ptr(RST_PTR, type, d0, d1, s0, s1)

/* Rastro function prototype for 'ddssd' */
void rst_event_ddssd_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, double d1, const char* s0, const char* s1, double d2);
void rst_event_ddssd_f_ (int16_t *type, double* d0, double* d1, const char* s0, const char* s1, double* d2);
#define rst_event_ddssd(type, d0, d1, s0, s1, d2) rst_event_ddssd_ptr(RST_PTR, type, d0, d1, s0, s1, d2)

/* Rastro function prototype for 'ddsss' */
void rst_event_ddsss_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, double d1, const char* s0, const char* s1, const char* s2);
void rst_event_ddsss_f_ (int16_t *type, double* d0, double* d1, const char* s0, const char* s1, const char* s2);
#define rst_event_ddsss(type, d0, d1, s0, s1, s2) rst_event_ddsss_ptr(RST_PTR, type, d0, d1, s0, s1, s2)

/* Rastro function prototype for 'ddsssd' */
void rst_event_ddsssd_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, double d1, const char* s0, const char* s1, const char* s2, double d2);
void rst_event_ddsssd_f_ (int16_t *type, double* d0, double* d1, const char* s0, const char* s1, const char* s2, double* d2);
#define rst_event_ddsssd(type, d0, d1, s0, s1, s2, d2) rst_event_ddsssd_ptr(RST_PTR, type, d0, d1, s0, s1, s2, d2)

/* Rastro function prototype for 'ddsssss' */
void rst_event_ddsssss_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, double d1, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4);
void rst_event_ddsssss_f_ (int16_t *type, double* d0, double* d1, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4);
#define rst_event_ddsssss(type, d0, d1, s0, s1, s2, s3, s4) rst_event_ddsssss_ptr(RST_PTR, type, d0, d1, s0, s1, s2, s3, s4)

/* Rastro function prototype for 'ddsssssd' */
void rst_event_ddsssssd_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, double d1, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, double d2);
void rst_event_ddsssssd_f_ (int16_t *type, double* d0, double* d1, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, double* d2);
#define rst_event_ddsssssd(type, d0, d1, s0, s1, s2, s3, s4, d2) rst_event_ddsssssd_ptr(RST_PTR, type, d0, d1, s0, s1, s2, s3, s4, d2)

/* Rastro function prototype for 'ddsssssid' */
void rst_event_ddsssssid_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, double d1, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, u_int32_t i0, double d2);
void rst_event_ddsssssid_f_ (int16_t *type, double* d0, double* d1, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, int32_t* i0, double* d2);
#define rst_event_ddsssssid(type, d0, d1, s0, s1, s2, s3, s4, i0, d2) rst_event_ddsssssid_ptr(RST_PTR, type, d0, d1, s0, s1, s2, s3, s4, i0, d2)

void rst_init_f_(int64_t *id1, int64_t *id2);
void rst_finalize_f_ (void);

#endif //__AUTO_RASTRO_FILE_H__
