/* Do not edit. File generated by rastro. */

#include "poti_header_rastro.h"

/* Rastro function implementation for 'iiiiiii' */
void rst_event_iiiiiii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1, u_int32_t i2, u_int32_t i3, u_int32_t i4, u_int32_t i5, u_int32_t i6)
{
  rst_startevent(ptr, type<<18|0x7777);
  RST_PUT(ptr, u_int32_t, 0x27770000);
  RST_PUT(ptr, u_int32_t, i0);
  RST_PUT(ptr, u_int32_t, i1);
  RST_PUT(ptr, u_int32_t, i2);
  RST_PUT(ptr, u_int32_t, i3);
  RST_PUT(ptr, u_int32_t, i4);
  RST_PUT(ptr, u_int32_t, i5);
  RST_PUT(ptr, u_int32_t, i6);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'iiiiiii' - fortran support */
void rst_event_iiiiiii_f_( int16_t *type, int32_t* i0, int32_t* i1, int32_t* i2, int32_t* i3, int32_t* i4, int32_t* i5, int32_t* i6)
{
  rst_event_iiiiiii ((u_int16_t)* type, (u_int32_t)* i0, (u_int32_t)* i1, (u_int32_t)* i2, (u_int32_t)* i3, (u_int32_t)* i4, (u_int32_t)* i5, (u_int32_t)* i6);
}

/* Rastro function implementation for 'iiiiiiiii' */
void rst_event_iiiiiiiii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1, u_int32_t i2, u_int32_t i3, u_int32_t i4, u_int32_t i5, u_int32_t i6, u_int32_t i7, u_int32_t i8)
{
  rst_startevent(ptr, type<<18|0x7777);
  RST_PUT(ptr, u_int32_t, 0x27777700);
  RST_PUT(ptr, u_int32_t, i0);
  RST_PUT(ptr, u_int32_t, i1);
  RST_PUT(ptr, u_int32_t, i2);
  RST_PUT(ptr, u_int32_t, i3);
  RST_PUT(ptr, u_int32_t, i4);
  RST_PUT(ptr, u_int32_t, i5);
  RST_PUT(ptr, u_int32_t, i6);
  RST_PUT(ptr, u_int32_t, i7);
  RST_PUT(ptr, u_int32_t, i8);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'iiiiiiiii' - fortran support */
void rst_event_iiiiiiiii_f_( int16_t *type, int32_t* i0, int32_t* i1, int32_t* i2, int32_t* i3, int32_t* i4, int32_t* i5, int32_t* i6, int32_t* i7, int32_t* i8)
{
  rst_event_iiiiiiiii ((u_int16_t)* type, (u_int32_t)* i0, (u_int32_t)* i1, (u_int32_t)* i2, (u_int32_t)* i3, (u_int32_t)* i4, (u_int32_t)* i5, (u_int32_t)* i6, (u_int32_t)* i7, (u_int32_t)* i8);
}

/* Rastro function implementation for 'iiiiiiiiiii' */
void rst_event_iiiiiiiiiii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1, u_int32_t i2, u_int32_t i3, u_int32_t i4, u_int32_t i5, u_int32_t i6, u_int32_t i7, u_int32_t i8, u_int32_t i9, u_int32_t i10)
{
  rst_startevent(ptr, type<<18|0x7777);
  RST_PUT(ptr, u_int32_t, 0x27777777);
  RST_PUT(ptr, u_int32_t, i0);
  RST_PUT(ptr, u_int32_t, i1);
  RST_PUT(ptr, u_int32_t, i2);
  RST_PUT(ptr, u_int32_t, i3);
  RST_PUT(ptr, u_int32_t, i4);
  RST_PUT(ptr, u_int32_t, i5);
  RST_PUT(ptr, u_int32_t, i6);
  RST_PUT(ptr, u_int32_t, i7);
  RST_PUT(ptr, u_int32_t, i8);
  RST_PUT(ptr, u_int32_t, i9);
  RST_PUT(ptr, u_int32_t, i10);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'iiiiiiiiiii' - fortran support */
void rst_event_iiiiiiiiiii_f_( int16_t *type, int32_t* i0, int32_t* i1, int32_t* i2, int32_t* i3, int32_t* i4, int32_t* i5, int32_t* i6, int32_t* i7, int32_t* i8, int32_t* i9, int32_t* i10)
{
  rst_event_iiiiiiiiiii ((u_int16_t)* type, (u_int32_t)* i0, (u_int32_t)* i1, (u_int32_t)* i2, (u_int32_t)* i3, (u_int32_t)* i4, (u_int32_t)* i5, (u_int32_t)* i6, (u_int32_t)* i7, (u_int32_t)* i8, (u_int32_t)* i9, (u_int32_t)* i10);
}

/* Rastro function implementation for 'iiiiiiiiiiiii' */
void rst_event_iiiiiiiiiiiii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1, u_int32_t i2, u_int32_t i3, u_int32_t i4, u_int32_t i5, u_int32_t i6, u_int32_t i7, u_int32_t i8, u_int32_t i9, u_int32_t i10, u_int32_t i11, u_int32_t i12)
{
  rst_startevent(ptr, type<<18|0x7777);
  RST_PUT(ptr, u_int32_t, 0x7777777);
  RST_PUT(ptr, u_int32_t, 0x27700000);
  RST_PUT(ptr, u_int32_t, i0);
  RST_PUT(ptr, u_int32_t, i1);
  RST_PUT(ptr, u_int32_t, i2);
  RST_PUT(ptr, u_int32_t, i3);
  RST_PUT(ptr, u_int32_t, i4);
  RST_PUT(ptr, u_int32_t, i5);
  RST_PUT(ptr, u_int32_t, i6);
  RST_PUT(ptr, u_int32_t, i7);
  RST_PUT(ptr, u_int32_t, i8);
  RST_PUT(ptr, u_int32_t, i9);
  RST_PUT(ptr, u_int32_t, i10);
  RST_PUT(ptr, u_int32_t, i11);
  RST_PUT(ptr, u_int32_t, i12);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'iiiiiiiiiiiii' - fortran support */
void rst_event_iiiiiiiiiiiii_f_( int16_t *type, int32_t* i0, int32_t* i1, int32_t* i2, int32_t* i3, int32_t* i4, int32_t* i5, int32_t* i6, int32_t* i7, int32_t* i8, int32_t* i9, int32_t* i10, int32_t* i11, int32_t* i12)
{
  rst_event_iiiiiiiiiiiii ((u_int16_t)* type, (u_int32_t)* i0, (u_int32_t)* i1, (u_int32_t)* i2, (u_int32_t)* i3, (u_int32_t)* i4, (u_int32_t)* i5, (u_int32_t)* i6, (u_int32_t)* i7, (u_int32_t)* i8, (u_int32_t)* i9, (u_int32_t)* i10, (u_int32_t)* i11, (u_int32_t)* i12);
}

/* Rastro function implementation for 'iiiiiiiiiiiiiii' */
void rst_event_iiiiiiiiiiiiiii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1, u_int32_t i2, u_int32_t i3, u_int32_t i4, u_int32_t i5, u_int32_t i6, u_int32_t i7, u_int32_t i8, u_int32_t i9, u_int32_t i10, u_int32_t i11, u_int32_t i12, u_int32_t i13, u_int32_t i14)
{
  rst_startevent(ptr, type<<18|0x7777);
  RST_PUT(ptr, u_int32_t, 0x7777777);
  RST_PUT(ptr, u_int32_t, 0x27777000);
  RST_PUT(ptr, u_int32_t, i0);
  RST_PUT(ptr, u_int32_t, i1);
  RST_PUT(ptr, u_int32_t, i2);
  RST_PUT(ptr, u_int32_t, i3);
  RST_PUT(ptr, u_int32_t, i4);
  RST_PUT(ptr, u_int32_t, i5);
  RST_PUT(ptr, u_int32_t, i6);
  RST_PUT(ptr, u_int32_t, i7);
  RST_PUT(ptr, u_int32_t, i8);
  RST_PUT(ptr, u_int32_t, i9);
  RST_PUT(ptr, u_int32_t, i10);
  RST_PUT(ptr, u_int32_t, i11);
  RST_PUT(ptr, u_int32_t, i12);
  RST_PUT(ptr, u_int32_t, i13);
  RST_PUT(ptr, u_int32_t, i14);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'iiiiiiiiiiiiiii' - fortran support */
void rst_event_iiiiiiiiiiiiiii_f_( int16_t *type, int32_t* i0, int32_t* i1, int32_t* i2, int32_t* i3, int32_t* i4, int32_t* i5, int32_t* i6, int32_t* i7, int32_t* i8, int32_t* i9, int32_t* i10, int32_t* i11, int32_t* i12, int32_t* i13, int32_t* i14)
{
  rst_event_iiiiiiiiiiiiiii ((u_int16_t)* type, (u_int32_t)* i0, (u_int32_t)* i1, (u_int32_t)* i2, (u_int32_t)* i3, (u_int32_t)* i4, (u_int32_t)* i5, (u_int32_t)* i6, (u_int32_t)* i7, (u_int32_t)* i8, (u_int32_t)* i9, (u_int32_t)* i10, (u_int32_t)* i11, (u_int32_t)* i12, (u_int32_t)* i13, (u_int32_t)* i14);
}

/* Rastro function implementation for 'iiiiiiiiiiiiiiiii' */
void rst_event_iiiiiiiiiiiiiiiii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1, u_int32_t i2, u_int32_t i3, u_int32_t i4, u_int32_t i5, u_int32_t i6, u_int32_t i7, u_int32_t i8, u_int32_t i9, u_int32_t i10, u_int32_t i11, u_int32_t i12, u_int32_t i13, u_int32_t i14, u_int32_t i15, u_int32_t i16)
{
  rst_startevent(ptr, type<<18|0x7777);
  RST_PUT(ptr, u_int32_t, 0x7777777);
  RST_PUT(ptr, u_int32_t, 0x27777770);
  RST_PUT(ptr, u_int32_t, i0);
  RST_PUT(ptr, u_int32_t, i1);
  RST_PUT(ptr, u_int32_t, i2);
  RST_PUT(ptr, u_int32_t, i3);
  RST_PUT(ptr, u_int32_t, i4);
  RST_PUT(ptr, u_int32_t, i5);
  RST_PUT(ptr, u_int32_t, i6);
  RST_PUT(ptr, u_int32_t, i7);
  RST_PUT(ptr, u_int32_t, i8);
  RST_PUT(ptr, u_int32_t, i9);
  RST_PUT(ptr, u_int32_t, i10);
  RST_PUT(ptr, u_int32_t, i11);
  RST_PUT(ptr, u_int32_t, i12);
  RST_PUT(ptr, u_int32_t, i13);
  RST_PUT(ptr, u_int32_t, i14);
  RST_PUT(ptr, u_int32_t, i15);
  RST_PUT(ptr, u_int32_t, i16);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'iiiiiiiiiiiiiiiii' - fortran support */
void rst_event_iiiiiiiiiiiiiiiii_f_( int16_t *type, int32_t* i0, int32_t* i1, int32_t* i2, int32_t* i3, int32_t* i4, int32_t* i5, int32_t* i6, int32_t* i7, int32_t* i8, int32_t* i9, int32_t* i10, int32_t* i11, int32_t* i12, int32_t* i13, int32_t* i14, int32_t* i15, int32_t* i16)
{
  rst_event_iiiiiiiiiiiiiiiii ((u_int16_t)* type, (u_int32_t)* i0, (u_int32_t)* i1, (u_int32_t)* i2, (u_int32_t)* i3, (u_int32_t)* i4, (u_int32_t)* i5, (u_int32_t)* i6, (u_int32_t)* i7, (u_int32_t)* i8, (u_int32_t)* i9, (u_int32_t)* i10, (u_int32_t)* i11, (u_int32_t)* i12, (u_int32_t)* i13, (u_int32_t)* i14, (u_int32_t)* i15, (u_int32_t)* i16);
}


