/* Do not edit. File generated by rastro. */

#include "../../include/poti_events_rastro.h"

/* Rastro function implementation for 'sss' */
void rst_event_sss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, const char* s2)
{
  rst_startevent(ptr, type<<18|0x21110);
  RST_PUT_STR(ptr, s0);
  RST_PUT_STR(ptr, s1);
  RST_PUT_STR(ptr, s2);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'sss' - fortran support */
void rst_event_sss_f_( int16_t *type, const char* s0, const char* s1, const char* s2)
{
  rst_event_sss ((u_int16_t)* type,  s0,  s1,  s2);
}

/* Rastro function implementation for 'ssss' */
void rst_event_ssss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, const char* s2, const char* s3)
{
  rst_startevent(ptr, type<<18|0x21111);
  RST_PUT_STR(ptr, s0);
  RST_PUT_STR(ptr, s1);
  RST_PUT_STR(ptr, s2);
  RST_PUT_STR(ptr, s3);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'ssss' - fortran support */
void rst_event_ssss_f_( int16_t *type, const char* s0, const char* s1, const char* s2, const char* s3)
{
  rst_event_ssss ((u_int16_t)* type,  s0,  s1,  s2,  s3);
}

/* Rastro function implementation for 'sssss' */
void rst_event_sssss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4)
{
  rst_startevent(ptr, type<<18|0x1111);
  RST_PUT(ptr, u_int32_t, 0x21000000);
  RST_PUT_STR(ptr, s0);
  RST_PUT_STR(ptr, s1);
  RST_PUT_STR(ptr, s2);
  RST_PUT_STR(ptr, s3);
  RST_PUT_STR(ptr, s4);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'sssss' - fortran support */
void rst_event_sssss_f_( int16_t *type, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4)
{
  rst_event_sssss ((u_int16_t)* type,  s0,  s1,  s2,  s3,  s4);
}

/* Rastro function implementation for 'dssss' */
void rst_event_dssss_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1, const char* s2, const char* s3)
{
  rst_startevent(ptr, type<<18|0x2111);
  RST_PUT(ptr, u_int32_t, 0x21000000);
  RST_PUT(ptr, double, d0);
  RST_PUT_STR(ptr, s0);
  RST_PUT_STR(ptr, s1);
  RST_PUT_STR(ptr, s2);
  RST_PUT_STR(ptr, s3);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'dssss' - fortran support */
void rst_event_dssss_f_( int16_t *type, double* d0, const char* s0, const char* s1, const char* s2, const char* s3)
{
  rst_event_dssss ((u_int16_t)* type, (double)* d0,  s0,  s1,  s2,  s3);
}

/* Rastro function implementation for 'dss' */
void rst_event_dss_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1)
{
  rst_startevent(ptr, type<<18|0x22110);
  RST_PUT(ptr, double, d0);
  RST_PUT_STR(ptr, s0);
  RST_PUT_STR(ptr, s1);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'dss' - fortran support */
void rst_event_dss_f_( int16_t *type, double* d0, const char* s0, const char* s1)
{
  rst_event_dss ((u_int16_t)* type, (double)* d0,  s0,  s1);
}

/* Rastro function implementation for 'dssd' */
void rst_event_dssd_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1, double d1)
{
  rst_startevent(ptr, type<<18|0x22211);
  RST_PUT(ptr, double, d0);
  RST_PUT(ptr, double, d1);
  RST_PUT_STR(ptr, s0);
  RST_PUT_STR(ptr, s1);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'dssd' - fortran support */
void rst_event_dssd_f_( int16_t *type, double* d0, const char* s0, const char* s1, double* d1)
{
  rst_event_dssd ((u_int16_t)* type, (double)* d0,  s0,  s1, (double)* d1);
}

/* Rastro function implementation for 'dsss' */
void rst_event_dsss_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1, const char* s2)
{
  rst_startevent(ptr, type<<18|0x22111);
  RST_PUT(ptr, double, d0);
  RST_PUT_STR(ptr, s0);
  RST_PUT_STR(ptr, s1);
  RST_PUT_STR(ptr, s2);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'dsss' - fortran support */
void rst_event_dsss_f_( int16_t *type, double* d0, const char* s0, const char* s1, const char* s2)
{
  rst_event_dsss ((u_int16_t)* type, (double)* d0,  s0,  s1,  s2);
}

/* Rastro function implementation for 'dsssi' */
void rst_event_dsssi_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1, const char* s2, u_int32_t i0)
{
  rst_startevent(ptr, type<<18|0x2711);
  RST_PUT(ptr, u_int32_t, 0x21000000);
  RST_PUT(ptr, double, d0);
  RST_PUT(ptr, u_int32_t, i0);
  RST_PUT_STR(ptr, s0);
  RST_PUT_STR(ptr, s1);
  RST_PUT_STR(ptr, s2);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'dsssi' - fortran support */
void rst_event_dsssi_f_( int16_t *type, double* d0, const char* s0, const char* s1, const char* s2, int32_t* i0)
{
  rst_event_dsssi ((u_int16_t)* type, (double)* d0,  s0,  s1,  s2, (u_int32_t)* i0);
}

/* Rastro function implementation for 'dsssss' */
void rst_event_dsssss_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4)
{
  rst_startevent(ptr, type<<18|0x2111);
  RST_PUT(ptr, u_int32_t, 0x21100000);
  RST_PUT(ptr, double, d0);
  RST_PUT_STR(ptr, s0);
  RST_PUT_STR(ptr, s1);
  RST_PUT_STR(ptr, s2);
  RST_PUT_STR(ptr, s3);
  RST_PUT_STR(ptr, s4);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'dsssss' - fortran support */
void rst_event_dsssss_f_( int16_t *type, double* d0, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4)
{
  rst_event_dsssss ((u_int16_t)* type, (double)* d0,  s0,  s1,  s2,  s3,  s4);
}

/* Rastro function implementation for 'dsssssi' */
void rst_event_dsssssi_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, u_int32_t i0)
{
  rst_startevent(ptr, type<<18|0x2711);
  RST_PUT(ptr, u_int32_t, 0x21110000);
  RST_PUT(ptr, double, d0);
  RST_PUT(ptr, u_int32_t, i0);
  RST_PUT_STR(ptr, s0);
  RST_PUT_STR(ptr, s1);
  RST_PUT_STR(ptr, s2);
  RST_PUT_STR(ptr, s3);
  RST_PUT_STR(ptr, s4);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'dsssssi' - fortran support */
void rst_event_dsssssi_f_( int16_t *type, double* d0, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, int32_t* i0)
{
  rst_event_dsssssi ((u_int16_t)* type, (double)* d0,  s0,  s1,  s2,  s3,  s4, (u_int32_t)* i0);
}

/* Rastro function implementation for 'dsssssii' */
void rst_event_dsssssii_ptr(rst_buffer_t *ptr, u_int16_t type, double d0, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, u_int32_t i0, u_int32_t i1)
{
  rst_startevent(ptr, type<<18|0x2771);
  RST_PUT(ptr, u_int32_t, 0x21111000);
  RST_PUT(ptr, double, d0);
  RST_PUT(ptr, u_int32_t, i0);
  RST_PUT(ptr, u_int32_t, i1);
  RST_PUT_STR(ptr, s0);
  RST_PUT_STR(ptr, s1);
  RST_PUT_STR(ptr, s2);
  RST_PUT_STR(ptr, s3);
  RST_PUT_STR(ptr, s4);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'dsssssii' - fortran support */
void rst_event_dsssssii_f_( int16_t *type, double* d0, const char* s0, const char* s1, const char* s2, const char* s3, const char* s4, int32_t* i0, int32_t* i1)
{
  rst_event_dsssssii ((u_int16_t)* type, (double)* d0,  s0,  s1,  s2,  s3,  s4, (u_int32_t)* i0, (u_int32_t)* i1);
}

void rst_init_f_(int64_t *id1, int64_t *id2)
{
  rst_init((u_int64_t)* id1, (u_int64_t)* id2);
}
void rst_finalize_f_ ()
{
  rst_finalize();
}
