/* Do not edit. File generated by rastro. */

#ifndef __AUTO_RASTRO_FILE_H__
#define __AUTO_RASTRO_FILE_H__
#include <rastro.h>

/* Rastro function prototype for 'ssisssss' */
void rst_event_ssisssss_ptr(rst_buffer_t *ptr, u_int16_t type, const char* s0, const char* s1, u_int32_t i0, const char* s2, const char* s3, const char* s4, const char* s5, const char* s6);
void rst_event_ssisssss_f_ (int16_t *type, const char* s0, const char* s1, int32_t* i0, const char* s2, const char* s3, const char* s4, const char* s5, const char* s6);

#define rst_event_ssisssss(type, s0, s1, i0, s2, s3, s4, s5, s6) rst_event_ssisssss_ptr(RST_PTR, type, s0, s1, i0, s2, s3, s4, s5, s6)

void rst_init_f_(int64_t *id1, int64_t *id2);
void rst_finalize_f_ (void);

#endif //__AUTO_RASTRO_FILE_H__
